### ISSUE TITLE
Install without CocoaPods

### ISSUE THREAD

**Issue by britishmonkey** [YardiSystems/YSRangeSlider#1]
Hi.

What is the process for installing this in my project without using CocoaPods?

Thanks.

**Comment by britishmonkey** [comment]
Don't worry about it - I decided just to write my own as only 3 small Swift files so hardly worth requiring CocoaPods at all for things like this

**Comment by bpoplauschi** [comment]
Great the you solved the problem. For manual installation, you can just clone the repo `git clone git@github.com:YardiSystems/YSRangeSlider.git` or download the files from Github.
